version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytcrew_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - MONGO_URI=${MONGO_URI} # Or "mongodb://host.docker.internal:27017/"
      - DB_NAME=${DB_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytcrew_worker
    command: celery -A agent.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    container_name: ytcrew_redis
    ports:
      - "6379:6379"
